### PR TITLE
Prep for HACS

### PR DESCRIPTION
**Pull request by SgtBatten**
No trying to force anything but I thought I would have a crack at prepping this for HACS for my own learning. My fireplace gets installed in 2 days. 

I've added Escea branding to HA as required with this pull request in progress https://github.com/home-assistant/brands/pull/3421 

This is still outstanding: Open up a PR for the custom integration on the Home Assistant
Python wheels repository https://github.com/home-assistant/wheels-custom-integrations

### CODE REVIEW

**Comment by SgtBatten** [comment]
Also need to add tags to the repository such as climate and fireplace.

**Comment by SgtBatten** [comment]
I have now done the Wheels pull request. https://github.com/home-assistant/wheels-custom-integrations/pull/624

**Comment by snikch** [comment]
LGTM. I added `climate` and `fireplace` to the repo topics, was that what you meant?

**Comment by SgtBatten** [comment]
Yep it just says you have to have some topics. They are used as keywords for hacs search I think.

**Comment by SgtBatten** [comment]
I did a pull request for HACS and ludeus merged it almost immediately. https://github.com/hacs/default/pull/1368

I think that means it will show up in HACS pretty soon

**Comment by sads2000** [comment]
Awesome. Great work - much appreciated. Love controlling our Escea fireplace through HA!

**Comment by snikch** [comment]
@SgtBatten I've made you a collaborator FYI.

Looks like an Action failed: https://github.com/snikch/climate.escea/runs/6583585800?check_suite_focus=true#step:10:511

**Comment by SgtBatten** [comment]
Screenshot_20220525-120434

**Comment by snikch** [comment]
:fire:

**Comment by khcnz** [comment]
Awesome nice work @SgtBatten!

**Pull request merged**
